Update pathval
chaijs/chai pull request #1527
Opened 2023-07-21 20:05 UTC by koddsson

Since it's now an ES Module! :)

2023-07-21 20:18 UTC, keithamus approved these changes

2023-07-21 20:19 UTC, 43081j approved these changes

2023-07-21 20:20 UTC, 43081j commented
Good catch! One step closer to pure esm 👀

2023-07-21 21:13 UTC, voxpelli requested changes
Would have to change from `require` to `import` here?

https://github.com/chaijs/chai/blob/1a8247f30dbe0f54268a9748ae673caec75d6bfe/lib/chai/utils/index.js#L11

2023-07-22 09:24 UTC, koddsson commented
> Would have to change from `require` to `import` here?

Nope, the file has already got `import` calls in the `5.x.x` branch which this PR is targeting.

2023-07-22 17:37 UTC, voxpelli approved these changes
Missed that this PR was targeting a non-main branch as it wasn't mentioned anywhere and I didn't think of looking at the target branch as its so rare for projects to merge towards a non-main branch.

I would suggest creating a milestone and/or tracking issue that can convey this context to new contributors.

2023-07-25 19:33 UTC, koddsson commented
@keithamus; I don't have merge rights, so I can't land this myself. 

It also might be good to remove node12 and node14 as required builds in the repo settings, since they are never going to be reported.

2023-07-25 21:18 UTC, keithamus commented
I've given you merge rights, so feel free to merge 👍

2023-07-26 07:21 UTC, merged