Update check-error
chaijs/chai pull request #1528
Opened 2023-07-21 20:49 UTC by koddsson

Since it's now an ES Module! :)

2023-07-21 21:02 UTC, keithamus approved these changes

2023-07-21 21:02 UTC, voxpelli commented
@koddsson I see a new release for `check-error` on npm, but nothing in https://github.com/chaijs/check-error – no new tag or commits that refers to `2.0.0`

As for chai itself, you need to alter how its loaded here:

https://github.com/chaijs/chai/blob/1a8247f30dbe0f54268a9748ae673caec75d6bfe/lib/chai/utils/index.js#L148

`require()` can't load ESM-modules, you have to use `(await import()).default` instead.

2023-07-21 21:03 UTC, voxpelli requested changes
See my previous comment

2023-07-22 09:23 UTC, koddsson commented
> As for chai itself, you need to alter how its loaded here:

I don't know what branch this file is in, but I'm targetting the `5.x.x` branch, which doesn't have the `require` function call.

2023-07-22 16:29 UTC, voxpelli commented
> I don't know what branch this file is in, but I'm targetting the `5.x.x` branch, which doesn't have the `require` function call.

Right, I missed that part as it wasn't mentioned in the PR itself and neither any link to any milestone or such :)

2023-07-22 16:29 UTC, voxpelli approved these changes

2023-07-25 19:33 UTC, koddsson commented
@keithamus; I don't have merge rights, so I can't land this myself. 

It also might be good to remove node12 and node14 as required builds in the repo settings, since they are never going to be reported.

2023-07-26 07:21 UTC, merged