Implement `iterable` assertion
chaijs/chai pull request #1592
Opened 2024-01-28 15:59 UTC by koddsson

Pulled this out of #1583 so that these PRs make more logical sense.

This PR implemensts a `iterable`/`isIterable` assertion that checks a given object for `Symbol.iterator` but notably excludes `string` which does have `Symbol.iterator` but we don't consider to be "iterable".

2024-01-28 18:04 UTC, keithamus reviewed
I’m curious why explicitly disallow string for this check?

2024-01-28 19:34 UTC, koddsson commented
> I’m curious why explicitly disallow string for this check?

You know, I don't remember why I put that in there. I have a vague memory of the `sameMembers` test needing this but looking at this in isolations makes me think that's probably a oversight.

2024-01-28 20:53 UTC, 43081j submitted a review, later dismissed

2024-01-28 21:18 UTC, keithamus requested changes
Is this bit meant to be part of this PR?

2024-01-29 05:42 UTC, koddsson commented
> Is this bit meant to be part of this PR?

Not sure if GitHub is glitching but I can't see what this is referring to. I assume it's the `isSubsetOf` changes in which case, it shouldn't have been included and I've removed those changes. Thanks :)

2024-01-29 09:56 UTC, keithamus approved these changes
I think this is good but I am still a little uneasy about overloading `.an()` too much.

2024-01-29 14:22 UTC, 43081j commented
> I think this is good but I am still a little uneasy about overloading `.an()` too much.

curious, do you prefer `.is.iterable` then? just so we're all on the same page for other changes in future

im guessing you're unsure of leaning heavily on `an` for many things, since over time chai would mostly be that one chain

2024-01-29 14:27 UTC, keithamus commented
I'd prefer each assertion (especially core assertions) to map to something that a user can reproduce with a single expression. It makes it far easier for us to document, and for users to internalise. If they know `.an()` is just Chai's shorthand for `[Symbol.toStringTag] =` then that's an easier way to think about it than having a mental lookup table to some alternative logic.

2024-01-29 22:47 UTC, 43081j commented
makes sense to me 👍 

thanks for the explanation, i do agree

2024-01-30 08:49 UTC, koddsson commented
> I think this is good but I am still a little uneasy about overloading `.an()` too much.

I'm happy to change this. I'd rather nip this in the bud now than trying to untangle it later.

2024-02-11 10:13 UTC, keithamus approved these changes
Great stuff

2024-02-11 10:40 UTC, merged